name: This is my pipeline

on:
  workflow_dispatch:

jobs:
  run_pipeline:
    name: This is my pipeline job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: step_1
        name: Step 1
        run: |
          echo "Hello from step 1"

      - id: step_2
        name: Step 2
        run: |
          echo "Hello from step 2"

      - id: step_3
        name: Step 3
        run: |
          echo "Hello from step 3"
  run_pipeline_2:
    name: This is my second pipeline job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: step_4
        name: Step 4
        run: |
          echo "Hello from step 4"

      - id: step_5
        name: Step 5
        run: |
          echo "Hello from step 5"

      - id: step_6
        name: Step 6
        run: |
          echo "Hello from step 6"

